-- Expand the curated FPS gear catalog without replacing existing UUIDs or player references.
-- Re-running this migration only refreshes presentation metadata for the same category/brand/model.
begin;

insert into public.gear_items (brand, model, category, image_url, specs, source_url)
values
  ('ATK', 'F1 Extreme', 'mouse', '/gear/atk-f1-extreme.webp', '{"weight":"35 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.atk.store/products/atk-blazing-sky-f1-series-wireless-mouse'),
  ('ATK', 'X1 Ultimate', 'mouse', '/gear/atk-x1-ultimate.webp', '{"weight":"54 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.atk.store/products/atk-blazing-sky-x1-series-wireless-mouse'),
  ('Endgame Gear', 'OP1 8K', 'mouse', null, '{"weight":"51.5 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.endgamegear.com/en-us/gaming-mice/op1-8k'),
  ('Finalmouse', 'Starlight-12', 'mouse', null, '{}'::jsonb, 'https://finalmouse.com/'),
  ('Finalmouse', 'UltralightX', 'mouse', null, '{"polling_rate":"8000 Hz"}'::jsonb, 'https://finalmouse.com/products/ultralightx'),
  ('Lamzu', 'Atlantis Mini Pro', 'mouse', null, '{"weight":"51 g","polling_rate":"4000 Hz"}'::jsonb, 'https://lamzu.com/products/lamzu-atlantis-mini-pro'),
  ('Lamzu', 'Atlantis OG V2 4K', 'mouse', null, '{"weight":"57 g","polling_rate":"4000 Hz"}'::jsonb, 'https://lamzu.com/products/lamzu-atlantis-og-v2-4k'),
  ('Lamzu', 'Inca', 'mouse', '/gear/lamzu-inca.webp', '{"weight":"40 g","polling_rate":"8000 Hz"}'::jsonb, 'https://lamzu.com/products/lamzu-inca'),
  ('Lamzu', 'Maya X', 'mouse', '/gear/lamzu-maya-x.webp', '{"weight":"47 g","polling_rate":"8000 Hz"}'::jsonb, 'https://lamzu.com/products/lamzu-maya-x'),
  ('Lamzu', 'Thorn', 'mouse', '/gear/lamzu-thorn.webp', '{"weight":"52 g","polling_rate":"4000 Hz"}'::jsonb, 'https://lamzu.com/products/lamzu-thorn-4k'),
  ('Logitech G', 'G Pro Wireless', 'mouse', null, '{"weight":"80 g","polling_rate":"1000 Hz"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-mice/pro-wireless-mouse.html'),
  ('Logitech G', 'G Pro X Superlight', 'mouse', null, '{"weight":"63 g","polling_rate":"1000 Hz"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-mice/pro-x-superlight-wireless-mouse.html'),
  ('Logitech G', 'G Pro X Superlight 2', 'mouse', '/gear/logitech-g-g-pro-x-superlight-2.webp', '{"weight":"60 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-mice/pro-x2-superlight-wireless-mouse.html'),
  ('Logitech G', 'G309 Lightspeed', 'mouse', null, '{"weight":"86 g","polling_rate":"1000 Hz"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-mice/g309-lightspeed-gaming-mouse.html'),
  ('Logitech G', 'G502 X Plus', 'mouse', null, '{"weight":"106 g","polling_rate":"1000 Hz"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-mice/g502-x-plus-wireless-lightforce.html'),
  ('Logitech G', 'G703 Lightspeed', 'mouse', null, '{"weight":"95 g","polling_rate":"1000 Hz"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-mice/g703-hero-wireless-gaming-mouse.html'),
  ('Ninjutso', 'Sora V2', 'mouse', null, '{"weight":"39 g","polling_rate":"8000 Hz"}'::jsonb, 'https://ninjutso.com/products/ninjutso-sora-v2'),
  ('Pulsar', 'X2 CrazyLight', 'mouse', '/gear/pulsar-x2-crazylight.webp', '{"weight":"35 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.pulsar.gg/products/x2-crazylight-gaming-mouse'),
  ('Pulsar', 'X2H V3', 'mouse', '/gear/pulsar-x2h-v3.webp', '{"weight":"54 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.pulsar.gg/products/x2h-v3-gaming-mouse'),
  ('Pulsar', 'X2V2', 'mouse', '/gear/pulsar-x2v2.webp', '{"weight":"53 g","polling_rate":"4000 Hz"}'::jsonb, 'https://www.pulsar.gg/products/x2v2-gaming-mouse'),
  ('Pulsar', 'Xlite V3', 'mouse', null, '{"weight":"55 g","polling_rate":"4000 Hz"}'::jsonb, 'https://www.pulsar.gg/products/xlite-v3-gaming-mouse'),
  ('Pulsar', 'Xlite V4', 'mouse', '/gear/pulsar-xlite-v4.webp', '{"polling_rate":"8000 Hz"}'::jsonb, 'https://www.pulsar.gg/products/xlite-v4-gaming-mouse'),
  ('Razer', 'Cobra Pro', 'mouse', null, '{"weight":"77 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.razer.com/gaming-mice/razer-cobra-pro'),
  ('Razer', 'DeathAdder V3 HyperSpeed', 'mouse', '/gear/razer-deathadder-v3-hyperspeed.webp', '{"weight":"55 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.razer.com/gaming-mice/razer-deathadder-v3-hyperspeed'),
  ('Razer', 'DeathAdder V3 Pro', 'mouse', '/gear/razer-deathadder-v3-pro.webp', '{"weight":"63 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.razer.com/gaming-mice/razer-deathadder-v3-pro'),
  ('Razer', 'DeathAdder V4 Pro', 'mouse', '/gear/razer-deathadder-v4-pro.webp', '{"weight":"56 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.razer.com/gaming-mice/razer-deathadder-v4-pro'),
  ('Razer', 'Orochi V2', 'mouse', null, '{"weight":"60 g","polling_rate":"1000 Hz"}'::jsonb, 'https://www.razer.com/gaming-mice/razer-orochi-v2'),
  ('Razer', 'Viper V2 Pro', 'mouse', '/gear/razer-viper-v2-pro.webp', '{"weight":"58 g","polling_rate":"4000 Hz"}'::jsonb, 'https://www.razer.com/gaming-mice/razer-viper-v2-pro'),
  ('Razer', 'Viper V3 HyperSpeed', 'mouse', '/gear/razer-viper-v3-hyperspeed.webp', '{"weight":"82 g","polling_rate":"4000 Hz"}'::jsonb, 'https://www.razer.com/gaming-mice/razer-viper-v3-hyperspeed'),
  ('Razer', 'Viper V3 Pro', 'mouse', '/gear/razer-viper-v3-pro.webp', '{"weight":"54 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.razer.com/gaming-mice/razer-viper-v3-pro'),
  ('VAXEE', 'E1 Wireless', 'mouse', null, '{"polling_rate":"4000 Hz"}'::jsonb, 'https://www.vaxee.co/en/product.php?act=view&id=234'),
  ('VAXEE', 'NP-01S Wireless', 'mouse', null, '{"weight":"68 g","polling_rate":"4000 Hz"}'::jsonb, 'https://www.vaxee.co/en/product.php?act=view&id=167'),
  ('VAXEE', 'OUTSET AX Wireless', 'mouse', null, '{"polling_rate":"4000 Hz"}'::jsonb, 'https://www.vaxee.co/en/product.php?act=view&id=223'),
  ('VAXEE', 'XE Wireless', 'mouse', null, '{"weight":"76 g","polling_rate":"4000 Hz"}'::jsonb, 'https://www.vaxee.co/en/product.php?act=view&id=153'),
  ('VGN', 'Dragonfly F1 Pro Max', 'mouse', null, '{"weight":"55 g","polling_rate":"4000 Hz"}'::jsonb, 'https://vgnlab.com/products/vgn-dragonfly-f1-series-wireless-mouse'),
  ('VXE', 'R1 Pro Max', 'mouse', null, '{"weight":"54 g","polling_rate":"4000 Hz"}'::jsonb, 'https://vxe.com/products/vxe-r1-series-wireless-mouse'),
  ('WLMouse', 'Beast X', 'mouse', null, '{"weight":"39 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.wlmouse.com/products/beast-x'),
  ('WLMouse', 'Beast X Max', 'mouse', null, '{"weight":"42 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.wlmouse.com/products/beast-x-max'),
  ('WLMouse', 'Beast X Mini', 'mouse', null, '{"weight":"34 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.wlmouse.com/products/beast-x-mini'),
  ('WLMouse', 'Sword X', 'mouse', null, '{"weight":"47 g","polling_rate":"8000 Hz"}'::jsonb, 'https://www.wlmouse.com/products/sword-x'),
  ('ZOWIE', 'EC1-CW', 'mouse', '/gear/zowie-ec1-cw.webp', '{"polling_rate":"1000 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/mouse/ec1-cw.html'),
  ('ZOWIE', 'EC2-CW', 'mouse', '/gear/zowie-ec2-cw.webp', '{"polling_rate":"1000 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/mouse/ec2-cw.html'),
  ('ZOWIE', 'EC3-CW', 'mouse', '/gear/zowie-ec3-cw.webp', '{"polling_rate":"1000 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/mouse/ec3-cw.html'),
  ('ZOWIE', 'FK2-DW', 'mouse', '/gear/zowie-fk2-dw.webp', '{"polling_rate":"4000 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/mouse/fk2-dw.html'),
  ('ZOWIE', 'S2-DW', 'mouse', '/gear/zowie-s2-dw.webp', '{"polling_rate":"4000 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/mouse/s2-dw.html'),
  ('ZOWIE', 'U2-DW', 'mouse', '/gear/zowie-u2-dw.webp', '{"polling_rate":"4000 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/mouse/u2-dw.html'),
  ('ZOWIE', 'ZA13-DW', 'mouse', '/gear/zowie-za13-dw.webp', '{"polling_rate":"4000 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/mouse/za13-dw.html'),
  ('ASUS', 'ROG Azoth Extreme', 'keyboard', null, '{"layout":"75%","switch_type":"Mechanical"}'::jsonb, 'https://rog.asus.com/keyboards/keyboards/compact/rog-azoth-extreme/'),
  ('ASUS', 'ROG Falchion Ace HFX', 'keyboard', null, '{"layout":"65%","switch_type":"Hall effect"}'::jsonb, 'https://rog.asus.com/keyboards/keyboards/compact/rog-falchion-ace-hfx/'),
  ('ASUS', 'ROG Strix Scope II 96 Wireless', 'keyboard', null, '{"layout":"96%","switch_type":"Mechanical"}'::jsonb, 'https://rog.asus.com/keyboards/keyboards/compact/rog-strix-scope-ii-96-wireless/'),
  ('ATK', 'EDGE 60 HE', 'keyboard', null, '{"layout":"60%","switch_type":"Hall effect","polling_rate":"8000 Hz"}'::jsonb, 'https://www.atk.store/products/atk-edge-60-he-keyboard'),
  ('ATK', 'RS7 Pro', 'keyboard', null, '{"layout":"75%","switch_type":"Hall effect","polling_rate":"8000 Hz"}'::jsonb, 'https://www.atk.store/products/atk-rs7-series-mechanical-keyboard'),
  ('DrunkDeer', 'A75', 'keyboard', '/gear/drunkdeer-a75.webp', '{"layout":"75%","switch_type":"Hall effect"}'::jsonb, 'https://drunkdeer.com/products/drunkdeer-a75'),
  ('DrunkDeer', 'A75 Pro', 'keyboard', null, '{"layout":"75%","switch_type":"Hall effect"}'::jsonb, 'https://drunkdeer.com/products/drunkdeer-a75-pro'),
  ('DrunkDeer', 'G60', 'keyboard', null, '{"layout":"60%","switch_type":"Hall effect"}'::jsonb, 'https://drunkdeer.com/products/drunkdeer-g60'),
  ('Keychron', 'K2 HE', 'keyboard', null, '{"layout":"75%","switch_type":"Hall effect"}'::jsonb, 'https://www.keychron.com/products/keychron-k2-he-wireless-magnetic-switch-keyboard'),
  ('Keychron', 'Q1 HE', 'keyboard', null, '{"layout":"75%","switch_type":"Hall effect"}'::jsonb, 'https://www.keychron.com/products/keychron-q1-he-qmk-wireless-custom-keyboard'),
  ('Keychron', 'Q3 HE', 'keyboard', null, '{"layout":"TKL","switch_type":"Hall effect"}'::jsonb, 'https://www.keychron.com/products/keychron-q3-he-qmk-wireless-custom-keyboard'),
  ('MCHOSE', 'Ace 60 Pro', 'keyboard', null, '{"layout":"60%","switch_type":"Hall effect","polling_rate":"8000 Hz"}'::jsonb, 'https://www.mchose.store/products/mchose-ace-60-pro-magnetic-switch-keyboard'),
  ('MCHOSE', 'GX87', 'keyboard', null, '{"layout":"TKL","switch_type":"Mechanical"}'::jsonb, 'https://www.mchose.store/products/mchose-gx87-mechanical-keyboard'),
  ('Razer', 'Huntsman V3 Pro', 'keyboard', null, '{"layout":"Full size","switch_type":"Analog optical"}'::jsonb, 'https://www.razer.com/gaming-keyboards/razer-huntsman-v3-pro'),
  ('Razer', 'Huntsman V3 Pro Mini', 'keyboard', null, '{"layout":"60%","switch_type":"Analog optical"}'::jsonb, 'https://www.razer.com/gaming-keyboards/razer-huntsman-v3-pro-mini'),
  ('Razer', 'Huntsman V3 Pro TKL', 'keyboard', null, '{"layout":"TKL","switch_type":"Analog optical"}'::jsonb, 'https://www.razer.com/gaming-keyboards/razer-huntsman-v3-pro-tenkeyless'),
  ('SteelSeries', 'Apex Pro Gen 3', 'keyboard', null, '{"layout":"Full size","switch_type":"Hall effect"}'::jsonb, 'https://steelseries.com/gaming-keyboards/apex-pro-gen-3'),
  ('SteelSeries', 'Apex Pro Mini Wireless', 'keyboard', null, '{"layout":"60%","switch_type":"Hall effect"}'::jsonb, 'https://steelseries.com/gaming-keyboards/apex-pro-mini-wireless'),
  ('SteelSeries', 'Apex Pro TKL Gen 3', 'keyboard', null, '{"layout":"TKL","switch_type":"Hall effect"}'::jsonb, 'https://steelseries.com/gaming-keyboards/apex-pro-tkl-gen-3'),
  ('Wooting', '60HE', 'keyboard', '/gear/wooting-60he.webp', '{"layout":"60%","switch_type":"Hall effect"}'::jsonb, 'https://wooting.io/wooting-60he'),
  ('Wooting', '60HE v2', 'keyboard', '/gear/wooting-60he-v2.webp', '{"layout":"60%","switch_type":"Hall effect","polling_rate":"8000 Hz"}'::jsonb, 'https://wooting.io/wooting-60he-v2'),
  ('Wooting', '60HE+', 'keyboard', '/gear/wooting-60he-plus.webp', '{"layout":"60%","switch_type":"Hall effect"}'::jsonb, 'https://wooting.io/wooting-60he'),
  ('Wooting', '80HE', 'keyboard', '/gear/wooting-80he.webp', '{"layout":"80%","switch_type":"Hall effect"}'::jsonb, 'https://wooting.io/wooting-80he'),
  ('Wooting', 'Two HE', 'keyboard', '/gear/wooting-two-he.webp', '{"layout":"Full size","switch_type":"Hall effect","polling_rate":"1000 Hz"}'::jsonb, 'https://wooting.io/wooting-two-he'),
  ('ARTISAN', 'Hien Soft XL', 'mousepad', null, '{"surface":"Cloth","size":"XL"}'::jsonb, 'https://artisan-jp.com/nj_index_eng.html/'),
  ('ARTISAN', 'Key-83', 'mousepad', null, '{"surface":"Cloth"}'::jsonb, 'https://artisan-jp.com/nj_index_eng.html/'),
  ('ARTISAN', 'Raiden', 'mousepad', null, '{"surface":"Cloth"}'::jsonb, 'https://artisan-jp.com/nj_index_eng.html/'),
  ('ARTISAN', 'Type-99 Soft XL', 'mousepad', null, '{"surface":"Cloth","size":"XL"}'::jsonb, 'https://artisan-jp.com/nj_index_eng.html/'),
  ('ARTISAN', 'Zero Soft XL', 'mousepad', null, '{"surface":"Cloth","size":"XL"}'::jsonb, 'https://artisan-jp.com/nj_index_eng.html/'),
  ('Esports Tiger', 'Tang Dao SR', 'mousepad', null, '{"surface":"Cloth"}'::jsonb, 'https://www.esptiger.com/products/tang-dao-sr'),
  ('Lethal Gaming Gear', 'Jupiter Pro', 'mousepad', null, '{"surface":"Cloth"}'::jsonb, 'https://www.lethal.gg/products/jupiter-pro-series'),
  ('Lethal Gaming Gear', 'Saturn Pro', 'mousepad', null, '{"surface":"Cloth"}'::jsonb, 'https://www.lethal.gg/products/saturn-pro-series'),
  ('Lethal Gaming Gear', 'Venus Pro', 'mousepad', null, '{"surface":"Cloth"}'::jsonb, 'https://www.lethal.gg/products/venus-pro-series'),
  ('SteelSeries', 'QcK Heavy', 'mousepad', '/gear/steelseries-qck-heavy.webp', '{"surface":"Micro-woven cloth"}'::jsonb, 'https://steelseries.com/gaming-mousepads/qck-heavy'),
  ('SteelSeries', 'QcK Performance Balance', 'mousepad', null, '{"surface":"Cloth"}'::jsonb, 'https://steelseries.com/gaming-mousepads/qck-performance'),
  ('SteelSeries', 'QcK+', 'mousepad', null, '{"surface":"Micro-woven cloth"}'::jsonb, 'https://steelseries.com/gaming-mousepads/qck-series'),
  ('Wallhack', 'SP-004', 'mousepad', null, '{"surface":"Glass"}'::jsonb, 'https://wallhack.com/products/sp-004'),
  ('X-raypad', 'Aqua Control II', 'mousepad', null, '{"surface":"Hybrid cloth"}'::jsonb, 'https://shop.x-raypad.com/shop/x-raypad-aqua-control-ii-gaming-mouse-pads/'),
  ('X-raypad', 'Aqua Control Pro', 'mousepad', null, '{"surface":"Hybrid cloth"}'::jsonb, 'https://shop.x-raypad.com/shop/x-raypad-aqua-control-pro-gaming-mouse-pad/'),
  ('X-raypad', 'Equate Plus V2', 'mousepad', null, '{"surface":"Hybrid cloth"}'::jsonb, 'https://shop.x-raypad.com/shop/equate-plus-v2-kasumi-gaming-mouse-pads/'),
  ('ZOWIE', 'G-SR II', 'mousepad', '/gear/zowie-g-sr-ii.webp', '{"surface":"Cloth"}'::jsonb, 'https://zowie.benq.com/en-us/mouse-pad/g-sr-ii.html'),
  ('ZOWIE', 'G-SR-SE Rouge', 'mousepad', '/gear/zowie-g-sr-se-rouge.webp', '{"surface":"Cloth"}'::jsonb, 'https://zowie.benq.com/en-us/mouse-pad/g-sr-se-rouge.html'),
  ('ZOWIE', 'G-TR', 'mousepad', '/gear/zowie-g-tr.webp', '{"surface":"Cloth"}'::jsonb, 'https://zowie.benq.com/en-us/mouse-pad/g-tr.html'),
  ('ZOWIE', 'P-SR', 'mousepad', null, '{"surface":"Cloth"}'::jsonb, 'https://zowie.benq.com/en-us/mouse-pad/p-sr.html'),
  ('Alienware', 'AW2523HF', 'monitor', null, '{"resolution":"1920 × 1080","refresh_rate":"360 Hz"}'::jsonb, 'https://www.dell.com/en-us/shop/alienware-25-gaming-monitor-aw2523hf/apd/210-bfys/monitors-monitor-accessories'),
  ('Alienware', 'AW2524H', 'monitor', null, '{"resolution":"1920 × 1080","refresh_rate":"500 Hz"}'::jsonb, 'https://www.dell.com/en-us/shop/alienware-500hz-gaming-monitor-aw2524h/apd/210-bglm/monitors-monitor-accessories'),
  ('Alienware', 'AW2725DF', 'monitor', null, '{"resolution":"2560 × 1440","refresh_rate":"360 Hz"}'::jsonb, 'https://www.dell.com/en-us/shop/alienware-27-360hz-qd-oled-gaming-monitor-aw2725df/apd/210-bljd/monitors-monitor-accessories'),
  ('ASUS', 'PG248QP', 'monitor', null, '{"resolution":"1920 × 1080","refresh_rate":"540 Hz"}'::jsonb, 'https://rog.asus.com/monitors/23-to-24-5-inches/rog-swift-pro-pg248qp/'),
  ('ASUS', 'PG27AQDP', 'monitor', '/gear/asus-pg27aqdp.webp', '{"resolution":"2560 × 1440","refresh_rate":"480 Hz"}'::jsonb, 'https://rog.asus.com/monitors/27-to-31-5-inches/rog-swift-oled-pg27aqdp/'),
  ('ASUS', 'PG27AQN', 'monitor', null, '{"resolution":"2560 × 1440","refresh_rate":"360 Hz"}'::jsonb, 'https://rog.asus.com/monitors/27-to-31-5-inches/rog-swift-360hz-pg27aqn-model/'),
  ('ASUS', 'XG27ACDNG', 'monitor', '/gear/asus-xg27acdng.webp', '{"resolution":"2560 × 1440","refresh_rate":"360 Hz"}'::jsonb, 'https://rog.asus.com/monitors/27-to-31-5-inches/rog-strix-oled-xg27acdng/'),
  ('ASUS', 'XG27AQMR', 'monitor', null, '{"resolution":"2560 × 1440","refresh_rate":"300 Hz"}'::jsonb, 'https://rog.asus.com/monitors/27-to-31-5-inches/rog-strix-xg27aqmr/'),
  ('LG', '27GR95QE-B', 'monitor', null, '{"resolution":"2560 × 1440","refresh_rate":"240 Hz"}'::jsonb, 'https://www.lg.com/us/monitors/lg-27gr95qe-b-gaming-monitor'),
  ('LG', '27GS95QE-B', 'monitor', null, '{"resolution":"2560 × 1440","refresh_rate":"240 Hz"}'::jsonb, 'https://www.lg.com/us/monitors/lg-27gs95qe-b-gaming-monitor'),
  ('Samsung', 'Odyssey G7 G70B', 'monitor', null, '{"resolution":"3840 × 2160","refresh_rate":"144 Hz"}'::jsonb, 'https://www.samsung.com/us/computing/monitors/gaming/28-odyssey-g70b-4k-uhd-144hz-1ms-g-sync-gaming-monitor-ls28bg702enxgo/'),
  ('Samsung', 'Odyssey OLED G6 G60SD', 'monitor', null, '{"resolution":"2560 × 1440","refresh_rate":"360 Hz"}'::jsonb, 'https://www.samsung.com/us/computing/monitors/gaming/27-odyssey-oled-g6-g60sd-qhd-360hz-0-03ms-freesync-premium-pro-gaming-monitor-ls27dg602snxza/'),
  ('ZOWIE', 'XL2546K', 'monitor', null, '{"resolution":"1920 × 1080","refresh_rate":"240 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/monitor/xl2546k.html'),
  ('ZOWIE', 'XL2546X+', 'monitor', null, '{"resolution":"1920 × 1080","refresh_rate":"280 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/monitor/xl2546x-plus.html'),
  ('ZOWIE', 'XL2566K', 'monitor', null, '{"resolution":"1920 × 1080","refresh_rate":"360 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/monitor/xl2566k.html'),
  ('ZOWIE', 'XL2586X+', 'monitor', '/gear/zowie-xl2586x-plus.webp', '{"resolution":"1920 × 1080","refresh_rate":"600 Hz"}'::jsonb, 'https://zowie.benq.com/en-us/monitor/xl2586x-plus.html'),
  ('EPOS', 'GSP 600', 'headset', null, '{"connection":"Wired"}'::jsonb, 'https://www.eposaudio.com/en/us/gaming/products/gsp-600-gaming-headset-1000244'),
  ('EPOS', 'H6PRO Closed', 'headset', null, '{"connection":"Wired"}'::jsonb, 'https://www.eposaudio.com/en/us/gaming/products/h6pro-closed-green-gaming-headset-1000969'),
  ('HyperX', 'Cloud Alpha Wireless', 'headset', null, '{"connection":"Wireless","battery_life":"Up to 300 hours"}'::jsonb, 'https://hyperx.com/products/hyperx-cloud-alpha-wireless'),
  ('HyperX', 'Cloud II', 'headset', null, '{"connection":"Wired"}'::jsonb, 'https://hyperx.com/products/hyperx-cloud-ii'),
  ('HyperX', 'Cloud III', 'headset', null, '{"connection":"Wired"}'::jsonb, 'https://hyperx.com/products/hyperx-cloud-iii-wired-gaming-headset'),
  ('HyperX', 'Cloud III Wireless', 'headset', null, '{"connection":"Wireless","battery_life":"Up to 120 hours"}'::jsonb, 'https://hyperx.com/products/hyperx-cloud-iii-wireless-gaming-headset'),
  ('Logitech G', 'Astro A50 X', 'headset', null, '{"connection":"Wireless","battery_life":"Up to 24 hours"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-audio/a50-x-astro-wireless-headset-base-station.html'),
  ('Logitech G', 'Pro X 2', 'headset', null, '{"connection":"Wireless","battery_life":"Up to 50 hours"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-audio/pro-x-2-wireless-headset.981-001262.html'),
  ('Logitech G', 'Pro X Wireless', 'headset', null, '{"connection":"Wireless"}'::jsonb, 'https://www.logitechg.com/en-us/products/gaming-audio/pro-x-wireless-headset.981-000906.html'),
  ('Razer', 'BlackShark V2 HyperSpeed', 'headset', null, '{"connection":"Wireless","battery_life":"Up to 70 hours"}'::jsonb, 'https://www.razer.com/gaming-headsets/razer-blackshark-v2-hyperspeed'),
  ('Razer', 'BlackShark V2 Pro', 'headset', null, '{"connection":"Wireless","battery_life":"Up to 70 hours"}'::jsonb, 'https://www.razer.com/gaming-headsets/razer-blackshark-v2-pro-2023'),
  ('Razer', 'BlackShark V3 Pro', 'headset', '/gear/razer-blackshark-v3-pro.webp', '{"connection":"Wireless"}'::jsonb, 'https://www.razer.com/gaming-headsets/razer-blackshark-v3-pro'),
  ('SteelSeries', 'Arctis Nova 5', 'headset', null, '{"connection":"Wireless"}'::jsonb, 'https://steelseries.com/gaming-headsets/arctis-nova-5'),
  ('SteelSeries', 'Arctis Nova 7', 'headset', null, '{"connection":"Wireless"}'::jsonb, 'https://steelseries.com/gaming-headsets/arctis-nova-7'),
  ('SteelSeries', 'Arctis Nova Pro Wireless', 'headset', null, '{"connection":"Wireless"}'::jsonb, 'https://steelseries.com/gaming-headsets/arctis-nova-pro-wireless'),
  ('Corepad', 'Air', 'skates', null, '{"material":"PTFE"}'::jsonb, 'https://www.corepad.de/en/Corepad-Skatez-AIR/'),
  ('Corepad', 'CTRL', 'skates', null, '{"material":"PTFE"}'::jsonb, 'https://www.corepad.de/en/Corepad-Skatez-CTRL/'),
  ('Corepad', 'Pro Dots', 'skates', null, '{"material":"PTFE","format":"Dots"}'::jsonb, 'https://www.corepad.de/en/Corepad-Skatez-PRO/'),
  ('Corepad', 'Skatez PRO 280', 'skates', null, '{"material":"PTFE"}'::jsonb, 'https://www.corepad.de/en/Corepad-Skatez-PRO/'),
  ('Esports Tiger', 'Arc 1', 'skates', null, '{"material":"PTFE"}'::jsonb, null),
  ('Esports Tiger', 'ICE V2', 'skates', null, '{"material":"PTFE"}'::jsonb, null),
  ('Pulsar', 'Superglide', 'skates', null, '{"material":"Glass"}'::jsonb, 'https://www.pulsar.gg/products/superglide'),
  ('Pulsar', 'Superglide 2', 'skates', null, '{"material":"Glass"}'::jsonb, 'https://www.pulsar.gg/products/superglide-2'),
  ('X-raypad', 'Jade Air', 'skates', null, '{"material":"PTFE","format":"Dots"}'::jsonb, 'https://shop.x-raypad.com/shop/xraypad-jade-air-mouse-skates-universal-diy-dots/'),
  ('X-raypad', 'Jade Dot', 'skates', null, '{"material":"PTFE","format":"Dots"}'::jsonb, 'https://shop.x-raypad.com/shop/xraypad-jade-mouse-skates-universal-diy-dots/'),
  ('X-raypad', 'Obsidian Dot', 'skates', null, '{"material":"Hardened PTFE","format":"Dots"}'::jsonb, 'https://shop.x-raypad.com/shop/xraypad-obsidian-mouse-skates-universal-diy-dots/'),
  ('X-raypad', 'Obsidian Pro Air', 'skates', null, '{"format":"Dots"}'::jsonb, 'https://shop.x-raypad.com/shop/xraypad-obsidian-pro-air-mouse-skates-universal-diy-dots/')
on conflict (category, brand, model) do update
set image_url = excluded.image_url,
    specs = excluded.specs,
    source_url = excluded.source_url;

commit;
